// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg4Qdtn4Rxms9x6JOCQhNlFleg9U5oq80',
    appId: '1:115289343162:web:64dcb712854cb490626e83',
    messagingSenderId: '115289343162',
    projectId: 'todo-app1-aa9e3',
    authDomain: 'todo-app1-aa9e3.firebaseapp.com',
    storageBucket: 'todo-app1-aa9e3.appspot.com',
    measurementId: 'G-8VZ5G0D887',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ4UqmhkmXcwmZPjunftGgxyYMJ_saF2A',
    appId: '1:115289343162:android:bed8d2809e577311626e83',
    messagingSenderId: '115289343162',
    projectId: 'todo-app1-aa9e3',
    storageBucket: 'todo-app1-aa9e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwmt52iK3WguD_S3xlNEDDB_BWR52aNqk',
    appId: '1:115289343162:ios:ff407b3905baeabe626e83',
    messagingSenderId: '115289343162',
    projectId: 'todo-app1-aa9e3',
    storageBucket: 'todo-app1-aa9e3.appspot.com',
    iosBundleId: 'com.example.todoApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg4Qdtn4Rxms9x6JOCQhNlFleg9U5oq80',
    appId: '1:115289343162:web:2cc81316abff7c40626e83',
    messagingSenderId: '115289343162',
    projectId: 'todo-app1-aa9e3',
    authDomain: 'todo-app1-aa9e3.firebaseapp.com',
    storageBucket: 'todo-app1-aa9e3.appspot.com',
    measurementId: 'G-R0WGDDBW9N',
  );
}
